#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to
#your load-balancer IP (lb-01). Let’s also add other subdomains t
#ake our life easier, and write a Bash script that will display
#information about subdomains.

my_domain_innfo () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  my_domain_innfo "$1" "www"
  my_domain_innfo "$1" "lb-01"
  my_domain_innfo "$1" "web-01"
  my_domain_innfo "$1" "web-02"
elif [ "$#" == 2 ]
then
  my_domain_innfo "$1" "$2"
fi
