#!/usr/bin/env bash
#install NGINX

sudo apt-get -y update
sudo apt-get -y install nginx

sudo touch /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo chmod -R 755 /var/www/html

sudo cat > /var/www/html/index.html << EOF
Hello World!
EOF

printf %s "server {
	listen 80 default_server;
	listen		[::]:80 default_server;

	root		/var/www/html;
	index		index.html index.htm index.nginx-debian.html;

}
" > /etc/nginx/sites-available/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default &> /dev/null

service nginx start
