#!/usr/bin/env bash
#install NGINX

sudo apt-get -y update
sudo apt-get -y install nginx

sudo touch /var/www/html/index.html
sudo chown -R $USER:$USER /var/www/html/index.html
sudo chmod -R 755 /var/www/html
sudo echo "Hello world!" > /var/www/html/index.html


printf %s "server {
	listen 80 default_server;
	listen		[::]:80 default_server;

	root		/var/www/html;
	index		index.html index.htm index.nginx-debian.html;

}
" > /etc/nginx/sites-available/default


service nginx start
