#!/usr/bin/env bash
#install NGINX

apt-get -y update
apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello world!" > /var/www/html/index.html


printf %s "server {
	listen 80 default_server;
	listen		[::]:80 default_server;

	root		/var/www/html;
	index		index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default


service nginx restart
