#!/usr/bin/env bash
#install NGINX

apt-get -y update
apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello world!" > /var/www/html/index.html


printf %s "server {
	listen 80 default_server;
	listen		[::]:80 default_server;

	root		/var/www/html;
	index		index.html index.htm index.nginx-debian.html;
	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}

	location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}
" > /etc/nginx/sites-available/default


service nginx restart
