#!/usr/bin/env bash
#install NGINX

apt-get -y update
apt-get -y install nginx

touch /var/www/html/index.html  /var/www/html/404.html
echo "Hello world!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html


printf %s "server {
	listen 80 default_server;
	listen		[::]:80 default_server;

	root		/var/www/html;
	index		index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
                try_files \$uri \$uri/ =404;
        }

	location /redirect_me {
        return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
	}

	error_page 404 /404.html;
	location /404.html {
		internal;
	}
}
" > /etc/nginx/sites-available/default


service nginx restart
