#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server.
#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm

sudo apt-get update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

sudo cp  /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.back
tmp="
#front-end setup
frontend web1
        bind :80
        mode http

#back-end setup
backend server1
        balance roundrobin
        mode http
        server 104828-web-01 34.204.101.138:80 check
        server 104828-web-02 107.21.40.69:80 check
"
printf "%s" "$tmp" | sudo tee -a  /etc/haproxy/haproxy.cfg &> /dev/null
sudo service haproxy start

