#!/usr/bin/env bash
#displays:
#
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

list=$(ls)
for ele in $list
do
  echo "$ele" | cut -d '-' -f2
done
